{% set version = '1.0.1' %}

package:
  name: cnapy
  version: {{ version }}

source:
  git_url: https://github.com/cnapy-org/CNApy.git
  git_rev: v{{ version }}

requirements:
  build:
    - setuptools
    - pip
    - python=3.7
  run:
    - oct2py=5.2
    - openjdk=8
    - matplotlib-base
    - pip
    - python=3.7
    - qtpy=1.9
    - pyside2
    - appdirs
    - cobra=0.22
    - qtconsole=5.0
    - efmtool_link=0.0.3
    - optlang_enumerator=0.0.5

build:
  noarch: python
  number: 0  # NOTE: increment for new build/set to zero for new version
  script:
    - python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - cnapy = cnapy.__main__:main_cnapy
test:
  imports:
    - cnapy

about:
  home:  https://github.com/cnapy-org/CNApy
  license: Apache 2
  license_family: MIT
  license_file: LICENSE
  summary: An integrated environment for metabolic network analysis
  doc_url: https://github.com/cnapy-org/CNApy
  dev_url: https://github.com/cnapy-org/CNApy