{% set version = '1.1.4' %}

package:
  name: cnapy
  version: {{ version }}

source:
  git_url: https://github.com/cnapy-org/CNApy.git
  git_rev: v{{ version }}

requirements:
  channels:
    - cnapy
    - conda-forge
    - defaults
    - Gurobi
    - IBMDecisionOptimization
  build:
    - setuptools
    - pip
    - python=3.8
  run:
    - pydantic=1.10
    - matplotlib-base=3.6
    - pip=22
    - python=3.8
    - qtpy=2.3
    - pyqtwebengine=5.15
    - appdirs=1.4
    - cobra=0.25
    - qtconsole=5.4
    - requests=2.28
    - psutil=5.9
    - efmtool_link=0.0.4
    - optlang_enumerator>=0.0.8
    - straindesign>=1.9
    - nest-asyncio
    - gurobi
    - cplex
    - numpy<1.24

build:
  noarch: python
  number: 0  # NOTE: increment for new build/set to zero for new version
  script:
    - python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - cnapy = cnapy.__main__:main_cnapy
test:
  imports:
    - cnapy

about:
  home:  https://github.com/cnapy-org/CNApy
  license: Apache 2
  license_family: MIT
  license_file: LICENSE
  summary: An integrated environment for metabolic network analysis
  doc_url: https://github.com/cnapy-org/CNApy
  dev_url: https://github.com/cnapy-org/CNApy