= CNApy - A CellNetAnalyzer GUI in Python

image::cnapy/data/cnapylogo.svg[cnapy logo]


== Setup the CNApy development environment with conda

We use conda as package manager to install all dependencies. You can either use https://www.anaconda.com/[Anaconda] or https://docs.conda.io/en/latest/miniconda.html[miniconda].
If you have conda installed you can:

. Create a conda environment with all dependencies for cnapy from the environment.yml

.. on linux

  conda env create -f environment.yml

.. on windows

  conda env create -f winvironment.yml

. Activate the cnapy conda environment

  conda activate cnapy

. Download cnapy

.. either use `git`
      
  git clone https://github.com/ARB-Lab/CNApy.git

.. or click on the big green button above, download and unpack zip archive. The folder is then `CNApy-master` not `CNApy`.

. Change into the source directory and install CNApy
  
  cd CNApy
  python setup.py install

. Run cnapy
      
  cnapy


IMPORTANT: To use the CNA MATLAB functions you need atleast MATLAB 2019b and the Python API for the MATLAB engine installed and of course CNA

== Install Python API for MATLAB engine in MATLAB 2019b

First activate the cnapy conda environment

  conda activate cnapy

then

----
cd /usr/local/net/MATLAB/R2019b/extern/engines/python
python setup.py build --build-base="/scratch/mebuild" install
----

== Set CNA path

To use the CNA MATLAB functions you need to tell CNApy where CNA is installed.
Therefore, open or create a file `cnapy-config.txt` with the following content (change the path to your CNA path).

----
[cnapy-config]
cna_path = /my_folder/CellNetAnalyzer/
----

== How to run a script in the cnapy terminal

----
import testscript
testscript.work(cna)
----
