= CNApy - An integrated environment for metabolic model analysis

image::cnapy/data/cnapylogo.svg[cnapy logo,width=320,height=240]


== Install CNApy with conda

. Create a conda environment with all dependencies

   conda create -n cnapy-0.0.5 -c conda-forge -c cnapy cnapy

. Activate the cnapy conda environment

  conda activate cnapy-0.0.5

. Run CNApy
      
  cnapy


IMPORTANT: To use the CNA MATLAB functions you need atleast MATLAB 2019b and the Python API for the MATLAB engine installed and of course CNA. Alternatively you can also use Octave.


== How to run a script in the CNApy terminal

----
import testscript
testscript.work(cna)
----


== Setup the CNApy development environment with conda

We use conda as package manager to install all dependencies. You can use https://docs.conda.io/en/latest/miniconda.html[miniconda].
If you have conda installed you can:

  conda env create -n cnapy -f environment.yml


. Activate the cnapy conda environment

  conda activate cnapy

. Checkout the latest cnapy development version using git
      
  git clone https://github.com/cnapy-org/CNApy.git


. Change into the source directory and install CNApy
  
  ❯ cd CNApy

. Run CNApy
      
  python cnapy.py





== Contribution

https://github.com/cnapy-org/CNApy/blob/master/CONTRIBUTING.md[How to make a contribution to `CNApy`?]

Any contribution intentionally submitted for inclusion in the work by you, shall be licensed under the terms of the Apache 2.0 license without any additional terms or conditions.
