{% set version = '1.1.4' %}

package:
  name: cnapy
  version: {{ version }}

source:
  git_url: https://github.com/cnapy-org/CNApy.git
  git_rev: v{{ version }}

requirements:
  channels:
    - cnapy
    - conda-forge
    - defaults
    - Gurobi
    - IBMDecisionOptimization
  build:
    - setuptools
    - pip
    - python=3.8
  run:
    - pytest=7.1
    - pylint=2.13
    - autopep8=1.6
    - pydantic=1.9
    - matplotlib-base=3.5
    - python=3.8
    - qtpy=1.9
    - pyside2=5.13
    - appdirs=1.4
    - cobra=0.25
    - qtconsole=5.0
    - requests=2.27
    - psutil=5.9
    - efmtool_link=0.0.4
    - optlang_enumerator=0.0.7
    - straindesign>=1.9
    - gurobi
    - cplex

build:
  number: 0  # NOTE: increment for new build/set to zero for new version
  script:
    - python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - cnapy = cnapy.__main__:main_cnapy
test:
  imports:
    - cnapy

about:
  home:  https://github.com/cnapy-org/CNApy
  license: Apache 2
  license_family: MIT
  license_file: LICENSE
  summary: An integrated environment for metabolic network analysis
  doc_url: https://github.com/cnapy-org/CNApy
  dev_url: https://github.com/cnapy-org/CNApy